### ISSUE TITLE
Duplicate subscriptions to topic

### ISSUE THREAD

**Issue by cdpfeetfirst** [simonewebdesign/elixir_pubsub#6]
If a process subscribes twice to the same topic multiple copies are received of each message, one for each subscription.  Subsequent subscriptions should not add duplicate and could return :error tuple to indicate duplicate subscription.

```elixir
iex(1)> PubSub.start_link
{:ok, #PID<0.144.0>}
iex(2)> PubSub.subscribe(self(), :pubsub)
:ok
iex(3)> PubSub.subscribe(self(), :pubsub)
:ok
iex(4)> PubSub.subscribers(:pubsub)
[#PID<0.142.0>, #PID<0.142.0>]
iex(5)> PubSub.publish(:pubsub,"Duplicate messages")
:ok
iex(6)> Process.info(self(), :messages)
{:messages, ["Duplicate messages", "Duplicate messages"]}
```

**Comment by simonewebdesign** [comment]
I agree we could guard subscribers from this with an `{:error, :already_subscribed}` (or just `:error`). But I'm wondering if it makes more sense for it to be a no-op? After all, if you try to subscribe but you already are, you don't need to do anything.

Would you like to have a go at this?

**Comment by cdpfeetfirst** [comment]
Sure.  See pull-request #9, done as a no-op as suggested.
